version: '2'
services:
  api:
    image: openeats/api
    command: /startup/prod-entrypoint.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: "openeats"
      MYSQL_ROOT_PASSWORD: "root"
      API_URL: "0.0.0.0:8000"
      API_PORT: 8000
      DJANGO_SECRET_KEY: "sdfsadfas32e98zsdvhhsnz6udvbksjdhfi4galshjfg"
      DJANGO_SETTINGS_MODULE: "base.settings"
      DJANGO_DEBUG: "False"
      ALLOWED_HOST: "*"
  node:
    image: openeats/node
    command: npm start
    depends_on:
      - api
    environment:
      NODE_ENV: "production"
      NODE_URL: "localhost:8080"
      NODE_PORT: 8080
      NODE_API_URL: "http://my.domain.com"
      NODE_LOCALE: "en"
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: "openeats"
      MYSQL_ROOT_PASSWORD: "root"
  nginx:
    image: openeats/nginx
    command: ./start.sh
    ports:
      - "80:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    depends_on:
      - api
      - node
    environment:
      HTTP_X_FORWARDED_PROTO: "true"
volumes:
  database:
  static-files:
  site-media: